### ISSUE TITLE
Grid Definitions - Values for Stars?

### ISSUE THREAD

**Issue by freever** [VincentH-Net/CSharpForMarkup#10]
Hi

I am really starting to love this library, and I can't wait for it to be part of Xamarin.Forms. Death to XAML :)

I can't figure out a way to provide a value to GridLength.Star when defining rows and columns. As far as I can tell I can either provide a numberic value, which is used as GridLength.Absolute, or I can provide a GridLength of .Star or .Auto... but I cannot give a numeric value AND a GridLength. 

For example, if I want to create a grid with 3 columns, one of which is twice the size of the other two, I would do something like:

```c#
ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(2, GridUnitType.Star) });
```

Is there a snazzy way of doing this, like an overload that allows:

```c#
ColumnDefinitions = EnumsForGridRowsAndColumns.Columns.Define(
    (Cols.One, GridLength.Star, 1),
    (Cols.Two, GridLength.Star, 1),
    (ColsThree, GridLength.Star, 2));
```

Thanks!

**Comment by VincentH-Net** [comment]
Thanks @freever ! CSharpForMarkup is now [integrated in Xamarin.Forms 4.6](https://github.com/xamarin/Xamarin.Forms/pull/8342) (currently in preview release). It contains a lot of improvements (and quite a few helper renames so be aware of that) so I would encourage you to switch to that.

I already created a helper that does what you need: [commit](https://github.com/brminnick/XamConverter/pull/2/commits/5c0dca70afe91a1599f42b8b54845836617b5757)

```C#
public static GridLength Stars(double value) => new GridLength(value, GridUnitType.Star);
```
You can use it like this:
```C#
RowDefinitions = Rows.Define (
    (Row.ConvertedNumber, Star),
    (Row.ConvertButton  , Stars (2)))
```
This will be in the next Xamarin Forms CSharpForMarkup PR which will extend the merged one.
For now you can add the above extension method to your project and add a `using static` of the class that contains it.

**Comment by freever** [comment]
Thanks I will use that for now
