### ISSUE TITLE
MSBUILD : Custom warning : Injecting code into BindTap failed: Value cannot be null.

### ISSUE THREAD

**Issue by chrisofthecoffee** [VincentH-Net/CSharpForMarkup#11]
Hi there, I just started using your marvelous markup system and am most impressed, but I have come across a minor issue that I would appreciate some help with.

When I build my project including your XamarinFormsMarkupExtensions.cs I get the compiler warnings below;

1>MSBUILD : Custom warning : Injecting code into BindTap failed: Value cannot be null.
1>MSBUILD : Custom warning : Parameter name: method

It's not breaking anything, and commenting out the 3 BindTap interfaces from line 191 removes the warning but I thought you'd be interested to hear about it, I can't work out where the 'method' parameter it's talking about is so can't be of much help beyond this report.

I'm not using the interfaces at all, so I've left them commented out for now.

**Comment by mrwcjoughin** [comment]
@chrisofthecoffee have you tried the official C# for markup that is now part of Xamarin.Forms?
Basically as long as you're on Xamarin.Forms 4.6 or higher you can use it.
This project here was donated into the official as far as I know - so I assume that bugs will only be fixed there... 
The namespace there is Xamarin.Forms.Markup
I myself I have just started using it - though I'm starting with rewriting my styles from XAML into C# as I want to be able to use inheritance with them.
- [ ]

**Comment by chrisofthecoffee** [comment]
Ah, thanks, I spotted yesterday that the c# markup was now part of the official product but got the impression that XamarinFormsMarkupExtensions.cs was a useful set of helpers to go on top of that. 

Slight blush, I just renamed the namespace in the file and rebuiltand it seems I'm not using anything in there anyway.

Thanks, I think we can call this issue closed then !
