### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by baskren** [VincentH-Net/CSharpForMarkup#13]
@VincentH-Net  

First, thanks a million for taking the time to develop this.  I wish it existed 5 years ago when I started learning Xamarin.Forms.

FWIW,  I spent some time yesterday [implementing this concept in UWP / Uno](https://github.com/baskren/P42.Uno.Markup).  This morning I used it on another project and was amazed at how much less painful it was to build and maintain the layouts.

Binding in UWP is now a joy!

THANK YOU!

**Comment by VincentH-Net** [comment]
Thank you for your kind words @baskren! It's great to hear the concept being so useful on UWP / UNO.

FYI I'm working on C# Markup vNext for UNO. It will offer a _lot_ more than the current version. It looks promising but I have still quite some work to do before I am ready to go public with it. More goodness is coming. NJoy!

**Comment by baskren** [comment]
Very happy to learn you've got more in mind ... and that you're interested in UNO as well.  I would like to learn more when you're ready.
