### ISSUE TITLE
Create additional help for FontFamily

### ISSUE THREAD

**Issue by scottcg** [VincentH-Net/CSharpForMarkup#27]
FontFamily should allow strings (as XAML does)

```
.FontFamily(new FontFamily("Segoe UI"))
```

Could be 
```
.FontFamily("Segoe UI")
```

**Comment by VincentH-Net** [comment]
Currently this is supported; all properties that have a [TypeConvertor attribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverterattribute?view=net-6.0) in the UI framework get an extension method that accepts strings and converts them using the UI framework's convertors. There are also additional manual conversions for specific types from other types, e.g. `TimeSpan(double seconds)` or `Size((double width, double height))`

The supported conversions - both generated and manual - are implemented in the `to` namespace, e.g. `CSharpMarkup.WinUI.to.FontFamily`.

E.g. for WinUI see [WinUI.cs](https://github.com/VincentH-Net/CSharpForMarkup/blob/master/src/CSharpMarkup.WinUI/Generated/SourceGenerators/SourceGenerators.CsMarkupApiSourceGenerator/WinUI.cs) and [_TypeConvertors.cs](https://github.com/VincentH-Net/CSharpForMarkup/blob/master/src/CSharpMarkup.WinUI/_TypeConvertors.cs)
