### ISSUE TITLE
Does this compile back to XAML in the background ?

### ISSUE THREAD

**Issue by mrwcjoughin** [VincentH-Net/CSharpForMarkup#3]
Hi,

I have a question:
Does this compile back to XAML in the background ?

I currently already build my Xamarin.Forms UI's using code because of the terrible performance of using XAML it's self - so as long as this package doesn't compile back to XAML I would be very interested in trying it - especially to be able to move my only remaining XAML file left - which is for my Styles - to C#.

Thanks,

Matthew

**Comment by VincentH-Net** [comment]
Hi @mrwcjoughin,  no worries, this does not compile to XAML. These helpers are simply extremely thin calls to set properties on objects. All is fully pre-compiled and optimized by the C# compiler, like any C# code, including all bindings. Performance is as good as it gets.

Ps I also have helpers for declarative coded styles. I'll include those with an example shortly.

**Comment by mrwcjoughin** [comment]
Thanks, that sounds awesome. I will definitely try it out soonest :)

**Comment by VincentH-Net** [comment]
You're welcome :). I just added the **Style** helpers + ReadMe guidance; NJoy.

**Comment by mrwcjoughin** [comment]
Excellent, thanks 🎉🚀
