### ISSUE TITLE
What are some examples of CustomControls?

### ISSUE THREAD

**Issue by lukewire129** [VincentH-Net/CSharpForMarkup#41]
I have a situation where I need to create a CustomControl, and I've been stumped for days because I don't see any examples using DepencyProperty other than ControlTemplate in the current examples. 

I was wondering if there are any relevant examples

**Comment by VincentH-Net** [comment]
@lukewire129 the generated code for existing controls are your best examples here. Pick an existing control that resembles your custom control (or just a simple control), e.g. `Image`, and then open the generated source for that control (either with F12 or in this repo under `Generated`). You will see the source for that control within it's own namespace braces, e.g. `namespace CSharpMarkup.WinUI // Image`. You can also search for `// Image` with entire words option.

It will show you how to use `DependencyProperty`. Feel free to report back here if you need more help!
