### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by RomaRudyak** [VincentH-Net/CSharpForMarkup#6]
Hi, 

Very interesting Idea about C sharp for Markup.

Do you consider to create a NuGet package?

**Comment by VincentH-Net** [comment]
Not me myself but I created [this PR](https://github.com/xamarin/Xamarin.Forms/pull/8342) to include it in the [Xamarin Forms NuGet](https://www.nuget.org/packages/Xamarin.Forms/). 
If you like the PR let the Forms team know you want it. They are not moving fast with this.

**Comment by RomaRudyak** [comment]
Thank you for the approach
