### ISSUE TITLE
Row()/Col() bug 

### ISSUE THREAD

**Issue by westito** [VincentH-Net/CSharpForMarkup#7]
Remove "if (row != 0)" and simmilar "return if default value" conditions from Row/Col/ColSpan/RowCol/etc. functions. It took me days to realize my code not working because of this. I remove and re-add views from one grid to other and change order. Some of views not changed from row X to 0. This conditions are totally unnecessary!

**Comment by VincentH-Net** [comment]
Good catch! 
These checks are a minor performance improvement.
I did not encounter your scenario before; will remove them.

**Comment by VincentH-Net** [comment]
This is fixed in the Xamarin Forms (4.6) implementation
