### ISSUE TITLE
Register default properties using RegisterDefaultBindableProperties method

### ISSUE THREAD

**Issue by programmation** [VincentH-Net/CSharpForMarkup#8]
Is it possible to have the default properties dictionary filled in using the `RegisterDefaultBindableProperties` (or similar) method so all the configuration happens from one place?

**Comment by VincentH-Net** [comment]
It is possible, however I did not do that to avoid making devs call another init method in their apps, and to avoid a perf hit on app startup (small but still...).

In the version integrated in Xamarin Forms this is separate anyway, and it includes all built-in types where a default makes sense.
