### ISSUE TITLE
How to use RelativeLayout?

### ISSUE THREAD

**Issue by PatrickRyder** [VincentH-Net/CSharpForMarkup#9]
I need to use a **RelativeLayout** as a child of another screen element but I am struggling to see how I can do this in a declarative way, as the constraint is passed as a parameter to its **Add()** method.

Maybe a place for another helper, sort-of similar to the ones that allow enum names to be used for rows and columns in the **Grid** control?

**Comment by VincentH-Net** [comment]
Hi Patrick, yes I plan to add support for relative layout in the 'part 2' or in XamarinForms.

**Comment by VincentH-Net** [comment]
Hi Patrick; full support for `RelativeLayout` was included in [CSharpForMarkup Part 2 PR](https://github.com/xamarin/Xamarin.Forms/pull/11428)

If you can't wait for it to be merged, you can easily take the source files of the PR and add them to your app, for the time being.

**Comment by PatrickRyder** [comment]
Hi, Vincent,

That's excellent!

I'll wait for the merge, as I'm not doing anything with that bit of code right now.


  *   Patrick

________________________________
